### ISSUE TITLE
Knack formatting for equation type fields is not preserved

### ISSUE THREAD

**Issue by jenna-jordan** [cityofaustin/knackpy#109]
For equation fields, knackpy saves the same (raw) value as both the raw and formatted version of the value. However, the knack formatted version is preferred sometimes, such as when it is a datetime equation. The solution is likely to be adding a function for equation fields to the formatter.

So, here are a couple of snippets from the debugger when using knackpy:

```
records[0].fields['field_377'].formatted
372171.3180000782
records[0].fields['field_377'].raw
372171.3180000782

records_formatted[0]['Days Waiting - Security Review']
372171.3180000782
```

And here's a snippet from what we get from our knack script (run in debugger):

```
self.data_raw[0]['field_377']
4
self.data_raw[0]['field_377_raw']
372171.3180000782
```

Note that `372171.3180000782 / (60*60*24) = ~4.3` - in other words, the "raw" version returns the value in seconds, while the knack formatted version returns the value in days.

Here's another example (different record) - a snippet from the JSON export of the object:

`"field_377":5,"field_377_raw":434357.5299999714,`

**Comment by johnclary** [comment]
Thanks, Jenna! This is not a bug, but definitely not ideal behavior.

The good news is that the fix is easy. We can override Knackpy's default formatting behavior by adjusting the field settings, [here](https://github.com/cityofaustin/knackpy/blob/production/knackpy/models.py).

```python
FIELD_SETTINGS = {
   # ...
    "equation": {"use_knack_format": True}
}
```

`use_knack_format` will make sure that we pull the Knack formatted value for the equation field type. 
[Here's](https://github.com/cityofaustin/knackpy/blob/1663d165e3a26d1e27c999dbe156381e6349141a/knackpy/record.py#L128) where that happens in the code. 

If you're in a pinch, you can use that fix on a local copy of the package. 

I think this is a reasonable change to make to Knackpy permanently. Bearing in mind this will affect both date and number equation fields, this is definitely a breaking change. I'm going to flag it for `v1.1.0`.

**Comment by johnclary** [comment]
@jenna-jordan would you give this a test with the [knackpy-dev](https://pypi.org/project/knackpy-dev/) package?

**Comment by jenna-jordan** [comment]
Is it possible to parameterize the field_settings, so that can be changed in the code using knackpy, rather than the change having to happen in knackpy itself?

**Comment by johnclary** [comment]
I agree that would be a superior solution, but I'm headed on leave and will not be able to pick up that task in the near future. 

If you'd like to open a PR, by all means please do! In the meantime, I'm afraid you'll have to hack the existing API to get at what you need.
