### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by elrezad** [cityofaustin/knackpy#98]
Hi! Since last Friday I'm having an error when running 
`records=app.get('object_8')`

throwing this:
`File "/usr/local/lib/python3.7/dist-packages/knackpy/formatters.py", line 118, in <listcomp>
    identifiers = [conn["identifier"] for conn in value]
TypeError: string indices must be integers'

I'm able to get other objects (much smallers, the one that is giving problem has 8.5k records x 25 columns), so the problem should be on that db. Any suggestions of where or what should I look for?

Thanks

**Comment by johnclary** [comment]
@elrezad sorry to hear of your error. I believe you've encountered a bug. Would you be able to provide your app ID, or at least copy/paste the `object_8` field list from the [knack explorer](https://knack-explorer.austinmobility.io/) output?

**Comment by brandontoups** [comment]
Hey @johnclary, this isn't my issue but I believe I've been able to repro this for one of our apps. 

For us, it had to do with aa random string of characters in one of our `_raw` fields (I have raised this issue internally with Knack as well, but just wanted to let you know).

The specifics are as follows:
- a fetch from Knack's native API for object_1 for a specific record responds with the following (obfuscated just cause we don't know what it is and don't want to publish it lol)
```json
    "field_457": "",
    "field_457_raw": [
        "A",
        "B",
        "C",
        "D",
        " ",
        "E",
        "F",
        "G",
        "H",
        "I"
    ],
```
- this record is in object_1
- field_457 is a Connection to object_39

When knackpy pulls this record down and begins looping through each fields' formatters, 
- the line of code [here](https://github.com/cityofaustin/knackpy/blob/3bc2ba65871acf162b9d247817155aee5048db51/knackpy/formatters.py#L118) 
- with `value` equal to `['A', 'B', 'C', 'D', ' ', 'E', 'F', 'G', 'H', 'I']` (field_457_raw)
- tries to build a list comprehension on field_457_raw that fails because the letter "A" doesn't have a field `"identifier"`. And so on for letters B-I

I will let you know what I hear back from Knack about this, as it's really upstream of knackpy. If you'd like me to raise a PR anyways for 
```diff
-         identifiers = [conn["identifier"] for conn in value]
+         identifiers = [conn["identifier"] for conn in value if "identifier" in conn]
``` 
let me know. 


App-specific output for that app:

Connections
```
Retailer | object_39 | field_457 | outbound | one | many
```
Fields
```
Retailer | field_457 | connection
```
